create type status_pagamento_enum AS ENUM ('EM_ABERTO', 'FECHADO_COM_SUCESSO', 'FECHADO_FALHA_PAGAMENTO');

create table pagamentos (
                          id bigint generated by default as identity,
                          nome_cliente varchar(255),
                          email_cliente varchar(255),
                          valor_total_ordem_pagamento float(53),
                          status_pagamento status_pagamento_enum,
                          primary key (id)
);

insert into pagamentos (nome_cliente, email_cliente, valor_total_ordem_pagamento, status_pagamento)
values ('Adamastor', 'adamastor@email.com', 4999.90, 'EM_ABERTO');

insert into pagamentos (nome_cliente, email_cliente, valor_total_ordem_pagamento, status_pagamento)
values ('Adamastor', 'adamastor@email.com', 3599.00, 'FECHADO_COM_SUCESSO');

insert into pagamentos (nome_cliente, email_cliente, valor_total_ordem_pagamento, status_pagamento)
values ('Maristela', 'maristela@email.com', 899.99, 'EM_ABERTO');